# Generated by Django 6.0 on 2025-12-17 05:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing_comment_bid_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="User's available balance in dollars", max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='reserved_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Funds locked in open buy orders', max_digits=12),
        ),
    ]
